trigger:
  - master
  - ns2
  - refs/tags/*

pr:
  - master
  - ns2

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

jobs:
  # build the 
  - template: .ci/build.yml@components
    parameters:
      publishJob: windows
      areaPath: 'DevDiv\Xamarin SDK'
      linuxImage: '' # skip linux builds
      macosImage: '' # skip macos builds
      validPackagePrefixes:
        - Microsoft.Azure.Mobile.Client

  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - template: sign-artifacts/jobs/v1.yml@internal-templates
      parameters:
        dependsOn: [ 'build' ]
