# NOTE: the 'ns2' is currently the "main branch" for now. As soon as things are ready, it will be changed to whatever the main should be once merged.

trigger:
  - ns2
  - refs/tags/*

pr:
  - ns2

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

jobs:
  # build the 
  - template: .ci/build.yml@components
    parameters:
      masterBranchName: ns2
      publishJob: windows
      areaPath: 'DevDiv\Xamarin SDK'
      buildType: 'basic'
      # linuxImage: 'ubuntu-latest'
      validPackagePrefixes:
        - Microsoft.Azure.Mobile.Client

  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - template: sign-artifacts/jobs/v1.yml@internal-templates
      parameters:
        dependsOn: [ 'build' ]
